### PR TITLE
calc Command Fix

### PR DESCRIPTION
**Pull request by MrOwnership**
Fix to calc command that likely broke when mathjs was updated in #79. Was getting a `math.js eval is not a function` error.

image
image

### CODE REVIEW

**Comment by meleu** [comment]
thanks! :heart:
